before_script:
  - apt update
  - DEBIAN_FRONTEND=noninteractive apt install -y mono-runtime-common

stages:
  - build_and_test

stockmono:
  image: ubuntu:18.04
  stage: build_and_test
  script:
    - ./install_snapcraft_dockerless.sh
    # these exports below are needed to finish installation of dockerless snapcraft
    - export SNAP=/snap/snapcraft/current
    - export SNAP_NAME=snapcraft
    - export SNAP_ARCH=amd64
    - export PATH="/snap/bin:$PATH"

    - ./build_snap.sh

  artifacts:
    paths:
      - monocurl*.snap
    expire_in: 50days

