name: monocurl # you probably want to 'snapcraft register <name>'
base: core18
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

layout:
  /usr/share/.mono:
    symlink: $SNAP/etc/mono/certstore

apps:
  monocurl:
    command: sh $SNAP/usr/bin/mono-wrapper $SNAP/usr/bin/mono $SNAP/usr/lib/monocurl/monocurl.exe
    plugs: [network]

parts:
  monocurl:
    stage-packages:
      - libmono-system4.0-cil
      - mono-runtime
    build-packages:
      - build-essential
      - pkg-config
      - cli-common-dev
      - mono-devel
    plugin: make
    source: .

  certs:
    plugin: dump
    source: /etc/mono
    organize:
      certstore: etc/mono/certstore

  wrapper:
    plugin: dump
    source: .
    organize:
      mono-wrapper: usr/bin/mono-wrapper
