name: ubuntu

on: [push]

jobs:
  http_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: HTTP
      run: |
        ./build_and_run.sh http://httpvshttps.com/

  http_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: HTTP_SNAP
      run: |
        ./install_snapcraft.sh
        ./build_snap.sh
        ./run_snap.sh http://httpvshttps.com/

  oldhttps_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: oldHTTPS
      run: |
        ./build_and_run.sh https://raw.githubusercontent.com/knocte/geewallet/master/LICENCE.txt

  oldhttps_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: oldHTTPS_SNAP
      run: |
        ./install_snapcraft.sh
        ./build_snap.sh
        ./run_snap.sh https://raw.githubusercontent.com/knocte/geewallet/master/LICENCE.txt

  newhttps_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: newHTTPS
      run: |
        ./build_and_run.sh https://httpvshttps.com/

  newhttps_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: newHTTPS_SNAP
      run: |
        ./install_snapcraft.sh
        ./build_snap.sh
        ./run_snap.sh https://httpvshttps.com/
