name: ubuntu

on: [push]

jobs:
  stockmono_http_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: HTTP
      run: |
        ./downgrade_mono.sh
        ./build_and_run.sh http://httpvshttps.com/

  stockmono_http_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: HTTP_SNAP
      run: |
        ./downgrade_mono.sh
        ./build_snap.sh
        ./run_snap.sh http://httpvshttps.com/

  stockmono_oldhttps_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: oldHTTPS
      run: |
        ./downgrade_mono.sh
        ./build_and_run.sh https://raw.githubusercontent.com/knocte/geewallet/master/LICENCE.txt

  stockmono_oldhttps_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: oldHTTPS_SNAP
      run: |
        ./downgrade_mono.sh
        ./build_snap.sh
        ./run_snap.sh https://raw.githubusercontent.com/knocte/geewallet/master/LICENCE.txt

  stockmono_newhttps_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: newHTTPS
      run: |
        ./downgrade_mono.sh
        ./build_and_run.sh https://httpvshttps.com/

  stockmono_newhttps_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: newHTTPS_SNAP
      run: |
        ./downgrade_mono.sh
        ./build_snap.sh
        ./run_snap.sh https://httpvshttps.com/

  newmono_http_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: HTTP
      run: |
        ./build_and_run.sh http://httpvshttps.com/

  newmono_http_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: HTTP_SNAP
      run: |
        ./build_snap.sh
        ./run_snap.sh http://httpvshttps.com/

  newmono_oldhttps_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: oldHTTPS
      run: |
        ./build_and_run.sh https://raw.githubusercontent.com/knocte/geewallet/master/LICENCE.txt

  newmono_oldhttps_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: oldHTTPS_SNAP
      run: |
        ./build_snap.sh
        ./run_snap.sh https://raw.githubusercontent.com/knocte/geewallet/master/LICENCE.txt

  newmono_newhttps_outside_sandbox:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: newHTTPS
      run: |
        ./build_and_run.sh https://httpvshttps.com/

  newmono_newhttps_inside_snap:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: newHTTPS_SNAP
      run: |
        ./build_snap.sh
        ./run_snap.sh https://httpvshttps.com/
