name: ubuntu

on: [push]

jobs:
  ubuntu_build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and test snap
      run: |
        sudo apt install -y fsharp
        git submodule update --init
        ./downgradeMono.fsx
        sudo apt install -y snapd snapcraft
        snap --version
        snapcraft --version
        snapcraft
        sudo snap install --dangerous hello_0.1_amd64.snap
        mono stage/usr/lib/hello/hello-world.exe
        snap run hello
