name: ubuntu

on: [push]

jobs:
  ubuntu_build_and_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and test snap
      run: |
        sudo apt install -y fsharp
        git submodule update --init
        ./downgradeMono.fsx

        sudo apt install -y snapd
        sudo snap install --classic snapcraft

        # workaround for latest version of snapcraft to work on GithubActions/AzureDevOps
        sudo chown root:root /

        snap --version
        snapcraft --version

        snapcraft --destructive-mode
        sudo snap install --dangerous hello_0.1_amd64.snap

        mono stage/usr/lib/hello/hello-world.exe
        snap run hello
